<!DOCTYPE job-posting
  [<!ELEMENT job-posting (
    <!ELEMENT posting-information (posting-number, internal-recruitment, working-title, hiring-range, work-schedule, job-location, department, essential-job-duties, other-responsibilities)>
      <!ELEMENT posting-number (#PCDATA)>
      <!ELEMENT internal-recruitment (#PCDATA)>
      <!ELEMENT working-title (#PCDATA)>
      <!ELEMENT hiring-range (#PCDATA)>
      <!ELEMENT work-schedule (#PCDATA)>
      <!ELEMENT job-location (#PCDATA)>
      <!ELEMENT department (#PCDATA)>
      <!ELEMENT essential-job-duties (#PCDATA)>
      <!ELEMENT other-responsibilities (#PCDATA)>
    <!ELEMENT
    
          
